linters:
  # https://golangci-lint.run/usage/linters/#disabled-by-default
  fast: false

linter-settings:
  errcheck:
    check-type-assertions: true

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - bodyclose
