linters:
  # https://golangci-lint.run/usage/linters/#disabled-by-default
  fast: false
  disable:
    - cyclop
    - exhaustivestruct
    - exhaustruct
    - funlen
    - godox
    - gomnd
    - nlreturn
    - varnamelen

linter-settings:
  errcheck:
    check-type-assertions: true

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - bodyclose
